##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################


##############################################################
#
# Tools targets
#
##############################################################

TEST_TOOL_ROOTS := null procinstr showprocs-dynamic showprocs-static straggler-catcher

TOOL_LIBS += -lrt
TOOL_CXXFLAGS += -std=c++0x